version: '2'
services:

  postgres:
    image: postgres:10.5
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "pokedocs"

  keycloak:
    image: jboss/keycloak:9.0.3
    restart: always
    volumes:
        - "./realm-export.json:/tmp/realm-export.json"
    ports:
        - "8180:8080"
    environment:
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        DB_VENDOR: H2
        KEYCLOAK_IMPORT: /tmp/realm-export.json

  # quarkus_api:
  #   depends_on:
  #     - postgres
  #   build:
  #     context: .
  #     dockerfile: src/main/docker/Dockerfile.jvm
  #   ports:
  #     - "8080:8080"
  #     - "8443:8443"
  #   environment:
  #     QUARKUS_PROFILE: staging      